
const os = require("os")

console.log(os.freemem()/1024/1024/1024)
console.log(os.totalmem()/1024/1024/1024)
console.log(os.arch())
// console.log(os.cpus())
console.log(os.hostname())
console.log(os.machine())
console.log(os.type())
console.log(os.tmpdir())
console.log(os.homedir())
console.log(os.release())
// console.log(os.networkInterfaces())
console.log(os.platform())
console.log(os.EOL)